/*
 * Cargo <-> PlatformIO helper C file (autogenerated by cargo-pio)
 * This file is intentionally empty. Please DO NOT change it or delete it!
 *
 * Two reasons why this file is necessary:
 * - PlatformIO complains if the src directory is empty with an error message
 *   'Nothing to build. Please put your source code files to '../src' folder'. So we have to provide at least one C/C++ source file
 * - The Cargo invocation is attached as a post-action to building this file. This is necessary, or else
 *   Cargo crates will not see the extra include directories of all libraries downloaded via the PlatformIO Library Manager
 */
